version: 2.1

orbs:
  cypress: cypress-io/cypress@1.7.0

workflows:
  build:
    jobs:
      - cypress/install:
          yarn: true
      - cypress/run:
          name: dev
          requires:
            - cypress/install
          store_artifacts: true
          yarn: true
          start: yarn develop
          wait-on: "--timeout 30000 http://localhost:8000"
      - cypress/run:
          name: prod
          requires:
            - cypress/install
          store_artifacts: true
          yarn: true
          start: yarn serve
          wait-on: "--timeout 30000 http://localhost:8000"
