version: 2.1

orbs:
  cypress: cypress-io/cypress@1.7.0

workflows:
  build:
    jobs:
      - cypress/run:
          store_artifacts: true
          yarn: true
          start: yarn develop
          wait-on: "--timeout 20000 http://localhost:8000"
